### ISSUE TITLE
Matching the lhs in dplyr vs magrittr

### ISSUE THREAD

**Issue by steromano** [smbache/magrittr#10]
Not really an issue but more of a general comment.
Using the dplyr `%.%` operator, I got used to reference the left hand side in a chain as `__prev`, e.g.
```
iris %.% mutate(rownames = rownames(`__prev`))
```
This always felt a bit hacky, but actually worked fine in my experience.
While I do like the idea of replacing `__prev` with a nicer placeholder symbol, I am not convinced that `.` is best for the job. It seems that using `.` forces the implementation to only match the outmost call, in order to allow for the same symbol to be used _with a different meaning_ in inner formulas. So we can do stuff like
```
iris %>% aggregate(. ~ Species, ., mean)
```
(which is not particularly readable imo), but to reproduce my above dplyr code in magrittr I would need something like
```
iris %>% l(x -> mutate(x, rownames = rownames(x)))
```
(is there a better way?).
I was wondering if using a slightly "heavier" placeholder - maybe `._` or something like that - and actually have it mached in the full rhs, like `__prev` in dlyr, would actually turn out more powerful/readable.

**Comment by smbache** [comment]
I think the dot works fine as it is for now, with the distinction of whether or not it is nested.
