### ISSUE TITLE
FR: Pipe operators as S3/S4 methods

### ISSUE THREAD

**Issue by ctbrown** [smbache/magrittr#101]
@smbache,

Have you considered making pipe operators into S3 or S4 generics/methods to allow other developers to overload the pipe operators. Would you be interested in a pull request that does this or do you feel this should be accomplished in a separate package?

**Comment by hadley** [comment]
The pipe operators definitely should not be generics - the functions that you use the pipe with can be though.

**Comment by ctbrown** [comment]
@hadley,
I am unsure why you'd say that they "definitely should not be generics".  Other than being a somewhat difficult challenge is there a technical reason why they shouldn't.  I feel like I am missing something obvious.

**Comment by hadley** [comment]
Because the pipes do lexical transformation of code, they don't do any dispatch.  Could you provide an  example where you think making the pipe generic might do something?

**Comment by ctbrown** [comment]
@hadley 

Take Winston's R6 package for instance.  Currently, R6 permits accessing by the `$` operator only.  It would be nice to be able to use the magrittr's pipe for R6 objects, like this.

    R6Object %>% public_member %>% mean 
    R6Object %>% public_member <- 1:10

as opposed to 

    R6Object$public_member %>% mean 
    
I know this seems trivial but it really does improve code readability when you are using R6 with magrittr.   I have been playing around with it and think that it is possible with S4 methods and possibly with S3 methods.  I have S4 methods working for a single operator `%>%`, for instance.  I don't think it would be terribly difficult to extend that to longer chains, though I have not tried and might need some a little pointer from you or @smbache .

It is also likely possible to do this in its own package, magrittr.S4 (?), if it is preferred to keep some distance between implementations.     


Any alternative to this might be if magrittr treated recursive (list-like) object differently, by attempting to find the RHS on the object first.  That is, treat `%>%` like `%$%` if it can be. This would be in keeping with the design of `dplyr` and `data.table` where names on the data.frame/data.table are given priority.  Although this would introduce the possibility of name clashes, the occurrence would likely be small since names in recursive structures are usually_nouns and other functions are verbs.  The user could explicitly call functions and that can be done with the `::` operators if needed.  This could be accomplished changing only `magrittr::wrap_function` to test:

1. that LHS is recursive 
2. that the RHS can be de-referenced.

This would have the ancillary benefit that `%$%` would not be needed. 

Thoughts?

**Comment by smbache** [comment]
Fwiw, You can probably use `%$%` by specifying the `with` method appropriately, like this example I made for igraph: https://gist.github.com/smbache/282bf12bfcfc6ceaee1d

**Comment by gaborcsardi** [comment]
@ctbrown  I don't think 
```r
R6Object %>% public_member %>% mean 
```
is more readable than
```r
R6Object $ public_member %>% mean 
```
Why would it be? Because it uses the same operator twice? That makes it actually less readable, because you cannot tell whether `public_member` is a member or a non-member function without looking it up.

It is also dangerous. What if one of the packages you import adds `public_member` as a function? Should that be called then? Probably not. What if a base package adds it? So maybe if these name clashes happen you would want the member to have higher priority. But that is also dangerous if the class changes and a `public_member` member is added, because it might mask a non-member function.

I think it is much better to access the members with a different operator, simply because it is a very different operation.

**Comment by ctbrown** [comment]
@smbrache,

Thanks for the igraph link.  I will look at it.  

@gaborcsardi. 

I do think

    R6Object %>% public_member %>% mean
 
is more readable than

    R6Object $ public_member %>% mean 

It is not because it uses the same function twice, but because it uses one operator as opposed to two to do essentially the same thing ... dereference.  Most languages that use the `.` don't care about the distinction that R and magrittr make.  Having the developer worry about where a function exists seems pointless.  

As I said above, I don't agree that this is dangerous.  

1) IN the case of a base packages adding a function that masks the name that clashes: this would likely be a (very) rare occurrence, but more importantly as you pointed out the member (of the class) should be given higher priority.  This is what is done with `dplyr` and `data.table` and is one of the key features responsible for their success.  

2) IN the case of adding a new `public_member` to an existing class that masks another function...if this happens, then this would be more commonly what the developer is trying to do ... get the exact behavior that is advocated here.  Again, `data.table` and `dplyr` are the examples.  The users of `data.table` are `dplyr` are not distressed over this, but instead love that arguments perform introspection on the objects first.

Finally, I believe that these are not fundamentally different operations. They are falsely made so by R. Both are de-referencing operations. The only material difference is where they search. I would contend that DT/dplyr got it right and look to dereference *within* the recursive object first.

**Comment by hadley** [comment]
You argument seems to hinge on believing that `x$f()` and `f(x)` are fundamentally the same operation. But they're not - maybe in other languages, but not in R. I certainly wouldn't call `f(x)` a derefencing operation.

**Comment by ctbrown** [comment]
De-referencing ... in the sense of finding the object associated with the name `f`.  Implementation aside, the difference seems to largely where the interpreter searches for `f`.  It is hard to see how these are fundamentally different ... or even why they should be.   

How does the developer benefit as having these treated differently?

**Comment by ctbrown** [comment]
Well, that was particularly easy...implemented in < 15 lines of code.

     https://github.com/ctbrown/magrittr/tree/autoderef

While passing all existing tests.  

So I guess the question is whether you feel this is something that you'd like to have in `magrittr` or whether you I should put it in its own package that import `magrittr`. I am assuming from the dialogue above, the later is preferred.  And, if so, any preference or recommendation on how to release a derivative package?  I am thinking of doing a standard import / re-export thing.

Any objections?

**Comment by ctbrown** [comment]
I wonder if there is any interest in rethinking magrittr's behavior in light of [tidy evaluations](https://cran.r-project.org/web/packages/rlang/vignettes/tidy-evaluation.html) (opinionated @hadley ) scoping: data first, context next.  

I don't so much mean the S3/S4 generic aspect but the scoping aspect of introspecting names in the LHS first before looking to the context of the LHS.  

I suspect the answer is "the boat has sailed for magrittr".  

(FWIW, we have implemented this opinionated pipe and have been using it internally for over a year, with none of the dangers @gaborcsardi pointed out. It works with data.frames, data.tables, tibbles, lists, R6 objects, environments, hashes, etc. )
