### ISSUE TITLE
errors with list indexing using [[ notation

### ISSUE THREAD

**Issue by restonslacker** [smbache/magrittr#103]
I'm trying to understand why examples 2, 3, and 4 produce different errors.  I'm also curious to know why ex 2 doesn't produce the same result as ex 5. My guess is that this may be more of an issue with what it means to index a list using the bracket notation in R, than a `magrittr` specific problem, but I wanted to raise the issue.

```{r}
library("magrittr")
library("stringi")

# EX. 1 - works
"a:b" %>% stri_split_regex("a:")

# EX. 2 - error
# Error in stri_split_regex("a:") : 
#   argument "pattern" is missing, with no default
"a:b" %>% stri_split_regex("a:")[[1]][2]

# EX. 3 - error
# Error in stri_split_regex(pattern="a:") : 
#    argument "str" is missing, with no default
"a:b" %>% stri_split_regex(pattern="a:")[[1]][2]
  
# EX. 4 - error
# Error in .[stri_split_regex(str = ., pattern = "a:")[[1]], 2] : 
#   incorrect number of dimensions
"a:b" %>% stri_split_regex(str =., pattern="a:")[[1]][2]

# EX. 5 - works
("a:b" %>% stri_split_regex("a:"))[[1]][2]
```

Thanks!

**Comment by smbache** [comment]
think of all right-hand sides like this:

```R
a %>% b[[c]]
# is equivalent to
a %>% `[[`(b, c)
# which is equivalent to
a %>% `[[`(., b, c)
# which is then  
`[[`(a, b, c)
# or
a[[b, c]]
```

Similarly, things are not what they appear in your example above where a function call is "in between"...

In general with these kinds of RHS you should use ``a %>% `[[`(b)`` notation, or use the aliases, `extract` for `[` or `extract2` for `[[`:

```R
"a:b" %>% 
  stri_split_regex("a:") %>%
  extract2(1) %>% 
  extract(2)
```

I agree that the aliases in this case is a little verbose, so maybe clean it with a "verb":
```R
take_element <- function(x, i, j) x[[i]][j]

"a:b" %>% 
  stri_split_regex("a:") %>%
  take_element(2, 1)
```

**Comment by zerweck** [comment]
I may be having a related problem. I'm trying to pipe some integers to select elements from another vector, but i don't seem to be able to solve it with the given methods:
```R
    a <- 1
    b <- 2
    ls()
    [1] "a" "b"

    # What i want to do:
    ls()[c(2,1)]
    [1] "b" "a"

    # What i tried:
    c(2,1) %>% ls()[.]
    [1] NA NA
    c(2,1) %>% {ls()}[.]
    [1] NA NA
    c(2,1) %>% {ls()[.]}
    [1] NA NA
    c(2,1) %>% `[`(ls(),.)
    [1] NA NA
    c(2,1) %>% extract(a = ls(), b = .)
    [1] NA NA
```

Any ideas?

**Comment by hadley** [comment]
`ls() %>% .[c(2, 1)]`

**Comment by zerweck** [comment]
This was a simplified example, sorry for not making it clearer. I have a
more complex pipe where i want to pipe the selecting integers in the rhs
and i am wondering why it fails.

**Comment by zerweck** [comment]
Ahhh, i found it out. The problem is that the ls() between the pipe operators does not get evaluated in .GlobalEnv. 
```R
c(2,1) %>% ls(envir = .GlobalEnv)[.]
[1] "b" "a"
```
Sorry for bothering, moving along.

**Comment by restonslacker** [comment]
@smbache thanks for the explanation. It is much clearer now.
