### ISSUE TITLE
Possible to create conditional pipes?

### ISSUE THREAD

**Issue by jarodmeng** [smbache/magrittr#109]
Is it possible to add conditional eval into a piped workflow so depending on the eval result different actions are taken?

e.g., a %>% b %>% (test, d, e) will create path a %>% b %>% d when test evals to TRUE, but a %>% b %>% e otherwise.

**Comment by smbache** [comment]
Will `purrr::when` do?

https://github.com/hadley/purrr/blob/master/R/when.R

**Comment by jarodmeng** [comment]
Seems that `when` doesn't work with `%>%`.

```r
library(dplyr)
library(purrr)

mtcars %>%
  filter(mpg >= 15) %>%
  when(
    nrow(.) >= 10 ~ filter(., cyl > 4),
    ~ filter(, hp <= 150)
  )
```

This snippet works, but the following one gives an error.

```r
library(dplyr)
library(purrr)

mtcars %>%
  filter(mpg >= 15) %>%
  when(
    nrow(.) >= 10 ~ . %>% filter(cyl > 4),
    ~ . %>% filter(hp <= 150)
  )
```

For simple manipulation using one verb, I don't think it's a big problem to use the first snippet. However, sometimes, depending on the predicate, the operations afterwards can be complicated and being able to use `%>%` in those actions would be very valuable.

**Comment by smbache** [comment]
Remember that `. %>% foo %>% bar` is magrittr notation for defining a lambda function. This means that when `.` is to be treated as a value, it cannot be alone on the LHS. You can either avoid it, or have e.g. `(.)` as LHS inside the `when`.

**Comment by smbache** [comment]
I guess I'd prefer just having the dot inside the first verb, and then extend the pipeline as needed after.

**Comment by jarodmeng** [comment]
That makes sense. Thanks, Stefan. I guess this issue can be closed now.

**Comment by smbache** [comment]
No problem. Related is this function, where the conditioning is element-by-element. 

https://gist.github.com/smbache/d4d01e8b055838f4e30c

Although not in a package so far...

**Comment by ablack3** [comment]
How about this approach for creating conditional steps in a pipeline? `conditionally()` takes a function and returns a modified version of the function that has an additional `execute` argument. When `execute == TRUE`  the function will work as normal. When `execute == FALSE` the function will simply return its first argument unmodified.

    conditionally <- function(fun){
        function(first_arg, ..., execute){
            if(execute) return(fun(first_arg, ...))
            else return(first_arg)
        }
    }

    library(dplyr)
    cond_filter <- conditionally(filter)
    cond_select <- conditionally(select)

    mtcars %>%
        cond_filter(cyl == 4, execute = T) %>%
        cond_select(cyl, execute = F)
