### ISSUE TITLE
Possible to pipe the same data to two operations?

### ISSUE THREAD

**Issue by jcpetkovich** [smbache/magrittr#110]
I'm not sure how this would look, but I'm thinking something along the lines of haskell's `liftA2` function.

You can see `liftA2` in action here: https://wiki.haskell.org/Arrow_tutorial with an asciiart example of how it works.

I'm thinking it might look something like:

    x %>% pipe_split(. %>% f, . %>% g)  # returns a list of the results of f(x) g(x)

What do you think? Does this sound useful? I'm not entirely sure how to implement it, this is the first time I've really tried using NSE in R to do anything useful.

**Comment by smbache** [comment]
You can do

```R
x %>% {list(f(.), g(.)}
```

You can also use pipes inside the `{`-lambda, but then the dot would need to be "escaped" as to not produce a function, eg

```R
x %>% {list( (.) %>% f, (.) %>% g}
```

(Remember that plain `. %>% f %>% g` is short-hand for `function(.) f(.) %>% g` , loosely speaking.
Parenthesizing the dot is one way to get around that but not really that pretty. 

More generally I think this road of "non-linearity", branching pipelines in the way you describe, is not one we'll go down...

**Comment by jcpetkovich** [comment]
Fair enough, thanks for the help! Closing this.
