### ISSUE TITLE
Bug: Pipe operator fails when using a function with an explicit namespace

### ISSUE THREAD

**Issue by dirkschumacher** [smbache/magrittr#112]
The following code generates an error with magrittr_1.5 from CRAN:
`
1:10 %>% base::mean
`

Expected result should be `5.5` or the same as `1:10 %>% mean`

**Comment by smbache** [comment]
Yes. It has been fixed but has not made it to CRAN yet

**Comment by oganm** [comment]
I was wondering what happened to this fix on the 2.01 version
