### ISSUE TITLE
do.call inside pipe can't find .

### ISSUE THREAD

**Issue by cfhammill** [smbache/magrittr#113]
Not sure this is an issue or I just can't get my head around how the environments are working here:

```
add_two_numbers <- function(x, y, z){ x + y }
sub_two_numbers <- function(x, y, z){ x - y}

dispatching_function <- function(x, y, z = "a"){
  argument_list <- as.list(match.call())[-1] #take arguments throw away function symbol
  
  dispatched_function <-
    ifelse(z == "a", as.symbol("add_two_numbers"), as.symbol("sub_two_numbers"))
  
  do.call(eval(dispatched_function), argument_list)
}

5 %>% general_function(6, "a")
```

is unable to find "."
I've tried setting quote in do.call, and evaluating the call in the second parent frame, neither solves the problem. 

Any idea how to make it find the piped variable?

**Comment by smbache** [comment]
change

```R
do.call(eval(dispatched_function), argument_list)
```
to 
```R
do.call(eval(dispatched_function), list(x, y))
```
and forget about the `match.call`.

**Comment by cfhammill** [comment]
This is just a toy example, my actual dispatcher has 16 arguments, it would be nice if I didn't have to reiterate them in the list.

**Comment by smbache** [comment]
Then do:

```R
add_two_numbers <- function(x, y, z){ x + y }
sub_two_numbers <- function(x, y, z){ x - y}

dispatching_function <- function(x, y, z = "a")
{  
  arg_list <- lapply(names(formals()), as.symbol)
  
  dispatched_function <-
    ifelse(z == "a", as.symbol("add_two_numbers"), as.symbol("sub_two_numbers"))
  
  do.call(eval(dispatched_function), arg_list)
}

5 %>% dispatching_function(6, "a")

```

**Comment by smbache** [comment]
Or, alternatively (with a little additional cleaning):

```R
dispatching_function <- function(x, y, z = "a")
{  
  cl <- match.call()
  cl[[1L]] <- quote(list)
  args <- eval.parent(cl)
  
  fun <- `if`(z == "a", add_two_numbers, sub_two_numbers)
  
  do.call(fun, args)
}
```

**Comment by smbache** [comment]
I assume I can  close this now. As a final hint, you could reduce your code even further:

```R
dispatching_function <- function(x, y, z = "a")
{  
  cl <- match.call()
  cl[[1L]] <- `if`(z == "a", add_two_numbers, sub_two_numbers)
  eval.parent(cl)
}
```

**Comment by cfhammill** [comment]
Hi Stefan, sorry for the delay,

I first solution didn't quite work, it assumes the two functions have the exact same argument list. I haven't tried the other two but it looks like they will work, my solution was to force all the arguments and match the function to be dispatched and then
 `arg_list <- lapply(names(formals(dispatched_function)), as.symbol)`

Also that use of back-quoted if is really cool, thanks.

**Comment by smbache** [comment]
Re: ticked `if`: yeah `ifelse` is probably slower as it can do more. 

Also, see how `lm` matches the arguments passed on to `model.frame`, you may use that as inspiration.

**Comment by cfhammill** [comment]
Will do, thanks again

**Comment by smbache** [comment]
np
