### ISSUE TITLE
Memory Copy with %<>%

### ISSUE THREAD

**Issue by jaredlander** [smbache/magrittr#114]
I was playing around with the assignment pipe (`%<>%`) and noticed it does not have the same copy semantics as the regular assignment operator (`<-`).  Where `<-` only writes to memory for a new column, not the old columns, `%<>%` writes the entire data.frame to memory it seems.

Here's an example.

``` r
library(pryr)
library(dplyr)
library(magrittr)
data(diamonds, package='ggplot2')
dia1 <- diamonds
dia2 <- diamonds

object_size(diamonds, dia1)
```

    ## 3.46 MB

``` r
object_size(diamonds, dia2)
```

    ## 3.46 MB

``` r
object_size(dia1, dia2)
```

    ## 3.46 MB

``` r
object_size(diamonds, dia1, dia2)
```

    ## 3.46 MB

``` r
dia1 <- dia1 %>% mutate(Total=x + y + z)
dia2 %<>% mutate(Total=x + y + z)

object_size(diamonds, dia1)
```

    ## 3.89 MB

``` r
object_size(diamonds, dia2)
```

    ## 7.34 MB

``` r
object_size(dia1, dia2)
```

    ## 7.77 MB

``` r
object_size(diamonds, dia1, dia2)
```

    ## 7.77 MB

**Comment by smbache** [comment]
Weird. I made a fix for this in the simplified branch (https://github.com/smbache/magrittr/commit/120ce9470287de37162e81f52936e85fa7204c0b). 

Not sure why the original approach had that behaviour, but this one is probably clearner anyway.

Here's my output after:

```R
> library(magrittr)
> data(diamonds, package='ggplot2')
> dia1 <- diamonds
> dia2 <- diamonds
> 
> object_size(diamonds, dia1)
3.46 MB
> 
> object_size(diamonds, dia2)
3.46 MB
> 
> object_size(dia1, dia2)
3.46 MB
> 
> object_size(diamonds, dia1, dia2)
3.46 MB
> 
> dia1 <- dia1 %>% mutate(Total=x + y + z)
> dia2 %<>% mutate(Total=x + y + z)
> 
> object_size(diamonds, dia1)
3.89 MB
> 
> object_size(diamonds, dia2)
3.89 MB
> 
> object_size(dia1, dia2)
4.32 MB
> 
> object_size(diamonds, dia1, dia2)
4.32 MB
```

**Comment by jaredlander** [comment]
Looks great, I'll try to replicate.
