### ISSUE TITLE
deparse(substitute(.)) in a pipe

### ISSUE THREAD

**Issue by zerweck** [smbache/magrittr#115]
If I want to reference the name of an object itself, I currently only now about the `deparse(substitute(.))` workaround. It does not work in magrittr because `substitute()` only returns `value` in a pipe:
```R
> 1 %>% substitute
value
```

An example usage scenario would be to rename the columns of a data.frame from within a pipe with the table name as a prefix.

Is this something that will never be possible because the magrittr functions use `substitute()` themselves? Is there another way to reference the object name within the pipe?

**Comment by smbache** [comment]
Often there is no name, but you could write a function that will find the "lhs" symbol in the pipeline, given that this function is called from with a pipeline, which would refer to the left-most symbol/expression in the pipline. 

This will not be in magrittr itself, but FWIW. it would not be terribly difficult to write yourself. Something like:

```R
the_lhs <- function()
{
  parents <- lapply(sys.frames(), parent.env)
  
  is_magrittr_env <-
    vapply(parents, identical, logical(1), y = environment(`%>%`))
  
  if (any(is_magrittr_env)) {
    deparse(get("lhs", sys.frames()[[max(which(is_magrittr_env))]]))
  }
}


the_lhs() # invisibly NULL


> iris %>% head(2) %>% `colnames<-`(paste0(the_lhs(), ".", colnames(.)))

  iris.Sepal.Length iris.Sepal.Width iris.Petal.Length iris.Petal.Width iris.Species
1               5.1              3.5               1.4              0.2       setosa
2               4.9              3.0               1.4              0.2       setosa


> I(iris) %>% head(2) %>% `colnames<-`(paste0(the_lhs(), ".", colnames(.)))

  I(iris).Sepal.Length I(iris).Sepal.Width I(iris).Petal.Length I(iris).Petal.Width I(iris).Species
1                  5.1                 3.5                  1.4                 0.2          setosa
2                  4.9                 3.0                  1.4                 0.2          setosa

```
