### ISSUE TITLE
Math syntax when c(.) is used

### ISSUE THREAD

**Issue by philchalmers** [smbache/magrittr#116]
I'm sure this is known already, but thought it might be important to be made aware to others in case it isn't. This behaviour somewhat surprised me:

```r
set.seed(1)
x <- rnorm(100)
sqrt(sum((x - mean(x))^2) / (length(x) - 1))
sd(x)

[1] 0.8981994

(x - mean(x))^2 %>% sum %>% c(.) / (length(x) - 1) %>% sqrt

[1] 8.027181
```

I get that the fix is probably just to use `divide_by()` or wrap the whole statement in `sqrt()`, but it was somewhat troubling logically to think that the term `c(.) / (length(x) - 1)` isn't really passed to the last function.

**Comment by smbache** [comment]
There's nothing special about it. It's just operator precedence, like `2+2*5 != (2+2)*5`.

Also, asked here: https://github.com/smbache/magrittr/issues/104
