### ISSUE TITLE
Usagae of ! (negation) leads to incorrect/unexpected results

### ISSUE THREAD

**Issue by MilesMcBain** [smbache/magrittr#117]
Simple example:
```r
a <- c(TRUE,FALSE,NA)
!is.na(a) %>% which()
```
>[1] FALSE

Which is unexpected and nonsensical. Should be as per:
```r
a <- c(TRUE,FALSE,NA)
(!is.na(a)) %>% which() 
```
>[1] 1 2

Something to do with `!` not having an LHS maybe?

**Comment by krlmlr** [comment]
I think the reason is operator precedence, to me it looks like magrittr can do nothing about it:

```
!0 %*% 0
# TRUE
(!0) %*% 0
# 0
```

**Comment by smbache** [comment]
Indeed, as @krlmlr says, it's about operator precedence. 

You can do
```R
a %>% is.na %>% `!` %>% which
```

Although in this example, it's not winning you too much.
