### ISSUE TITLE
Allow piping into suppress* functions

### ISSUE THREAD

**Issue by ClaytonJY** [smbache/magrittr#119]
As far as I can tell, piping into a function like `suppressWarnings` doesn't actually suppress anything:
````
> suppressWarnings(as.integer("foobar"))
[1] NA
> as.integer("foobar") %>% suppressWarnings
[1] NA
Warning message:
In eval(expr, envir, enclos) : NAs introduced by coercion

> suppressMessages(message("foobar"))
> message("foobar") %>% suppressMessages
foobar
NULL
````

Is it possible to get these working as expected with the magrittr pipe? I know these aren't terribly common functions, but having to wrap a chain of piped operation is quite ugly compared to just adding another operation.

**Comment by smbache** [comment]
It won't be possible. Pipes evaluate LHS before RHS gets it.

**Comment by smbache** [comment]
I made a lazy evaluation pipe in the `simplified` branch, see here: https://github.com/smbache/magrittr/issues/120

**Comment by ClaytonJY** [comment]
@smbache thanks for mentioning this here, as I would have missed #120 otherwise. Looks very promising, and I patiently await the release of the `simplified` branch.
