### ISSUE TITLE
do.call equivalent

### ISSUE THREAD

**Issue by hh1985** [smbache/magrittr#125]
Hi,
For function `f <- function(data, arg1, arg2)`, I can use expression `do.call(f, list(data = 1, arg1 = 2, arg2 = 3))` to replace `f(1, 2, 3)`. I can do the same with `data %>% f(arg1, arg2)`. My question is, it is possible to use expression like `data %>% f(list(arg1, arg2))`? Passing argument list to function adds a lot of flexibility to interface design.

Thanks,

-hh1985

**Comment by smbache** [comment]
Is this what you want?

```R
top10 <-
  iris %>% 
  list(x = ., n = 10) %>% 
  do.call(what = head)
```

**Comment by hh1985** [comment]
@smbache This can definitely do what I need! 
In my scenario, `data` is generated in the wrapper function body and argument list is provided through wrapper function interface. When there is only one argument, I can use `data %>% head(n = 10)`. When there is a list of arguments, I still think it's nice to have things like `data %>% head(list(n = 10, ...))` for consistency reason. Currently I can stick to the style `c(list(data), arg_list) %>% do.call(func)`.  Thanks a lot!
