### ISSUE TITLE
Overriding pipe operators

### ISSUE THREAD

**Issue by jeroenjanssens** [smbache/magrittr#129]
Ever since I started using this great package, I often accidentally use `%>%` instead of `+` when working with `ggplot2`. I was hoping it would be possible to override the pipe operators. I tried the following:

```r
library(magrittr)
library(ggplot2)

`%>%` <- function(lhs, rhs) {
  if(is.ggplot(lhs) || is.ggproto(lhs)) {
    `+`(lhs, rhs)
  } else {
    magrittr::`%>%`(lhs, rhs)
  }
}
```

which makes the following possible:

```r
ggplot(iris, aes(Sepal.Width, Sepal.Length)) %>% geom_point()
```

Exactly what I want, but now "regular" invocations of `%>%` result in the following error message:

```r
> 1:5 %>% sum()
 Error in pipes[[i]] : subscript out of bounds 
```

Any pointers to how to solve this are greatly appreciated. Thanks.

**Comment by Breza** [comment]
I'll leave the troubleshooting to others, but this kind of function is risky because it makes your pipes a little more unpredictable for a minor benefit.

**Comment by jeroenjanssens** [comment]
Can you elaborate on why this would be unpredictable?

**Comment by smbache** [comment]
The pipe operator(s) in magrittr don't work the usual way; the first pipe to get invoked (in the sense `` `%>%`(foo %>% bar, baz)``, ie the right-most pipe) will "compile" the entire chain, rather than every pipe operator having to work out what to do sequentially. Therefore it is not really possible to override them. That said, I've seen people do this

```R
ggplot(...) %>%
  + geom_foo(...) %>%
  + geom_bar(...)
```

No pun intended with `geom_bar` ;-)

**Comment by jeroenjanssens** [comment]
Thanks for the explanation @smbache. In that case it might make more sense to override the appropriate functions in `ggplot2`:

```r
library(magrittr)
library(ggplot2)

geom_point <- function(g, ...) {
  g + ggplot2::geom_point(...)
}

facet_wrap <- function(g, ...) {
  g + ggplot2::facet_wrap(...)
}

ggplot(iris) %>%
  geom_point(aes(Sepal.Length, Petal.Width)) %>%
  facet_wrap(~ Species)
```

I'll see how far I get with this approach. It's only an experiment anyway. Thanks again!
