### ISSUE TITLE
Create backpipe %<% operator

### ISSUE THREAD

**Issue by ctbrown** [smbache/magrittr#26]
There are times when it is desirable to reverse the direction of the pipe operator to match the order of parenthesis.  The motivating example is a shiny application in which the shiny commands build up HTML.  A backpipe operator would preserve the hierarchy of the HTML while cleaning up the code immensely.  Consider:

    require(shiny)
    # Original Shiny: 
    div( class="color-green",  h1( "Header 1" ) )
   
    # Current magrittr:
    h1( "Header 1" ) %>% div( class="color-green" )    
    
    # proposed 
    div( class="color-green" )  %<% h1( "Header 1" ) 

The proposed syntax not only make the code more readable, but alos preserves the hierarchical nature of the HTML so the code more closely matches the generated HTML.

( BTW, I am already doing this with shiny application by simply cloning %>% and reversing the order of the arguments.  I have not investigated how this would work with the changes for 1.1.0.  I am happy to submit code if @smbache thinks this is a useful feature. )

**Comment by ctbrown** [comment]
Despite, you guys getting your yucks about ... ( looking at you Antonio ;) ) There does seem to be some interest in this:

http://stackoverflow.com/questions/31305342/is-right-to-left-operator-associativity-in-r-possible

**Comment by piccolbo** [comment]
It seems to me that the main point of %>% is how it rearranges tokens so that related things are closer together. I look at @ctbrown example and the one on SO and I don't see any rearrangement.

```
# Original Shiny: 
div( class="color-green",  h1( "Header 1" ) )

# proposed 
div( class="color-green" )  %<% h1( "Header 1" ) 
```
Order is identical, trading a comma for a %<%, one lowly parens moving a tiny bit. Am I trivializing things,  missing the point? Maybe an example with two consecutive uses of the operator levels would help me. 

Sorry for veering on the comedic side on the DAGs but I was serious about them. I will open another issue if anybody's interested.

**Comment by piccolbo** [comment]
Well, the SO example has three or more consecutive uses of %<% or equivalent.

**Comment by ctbrown** [comment]
@piccolbo 

No worries about the comedic side.  

Exactly! The utility of back-piping becomes more apparent with increased complexity.  Compare:

```
# Original Shiny:
     h1( div( class="color-green", div( class="text-bold", div( class="date", "2015-08-26" ) ) ) )

# Proposed
    h1 %<% 
       div( class="color-green" ) %<% 
       div( class="text-bold" ) %<% 
       div( class="date", "2015-08-26 ) 
```

The latter is more legible than the former. 

While it might be argued that `magrittr` as is, would be equally as legibly, the back-piping allows the operations to appear in the same order appears as the generated HTML.  This makes debugging infinitely easier.

What I might concede is that a backpipe operator does not belong in the `magrittr` package, but should be a different package, e.g. `magrittr.backpipe` or something so as not to overbloat magrittr.

Really my only point in posting is to be complete in the documentation of this issue and capture the additional data point of the SO post.

**Comment by piccolbo** [comment]
I always write my code that way and I don't have any backpipes! I write my code so that indentation is proportional to depth in the parse tree for the n top levels, and on one line below n, n varies a little bit heuristically, I must admit. I am also thinking about a formatter that automates this approach. 

```
    h1(
       div( class="color-green" ),
       div( class="text-bold" ),
       div( class="date", "2015-08-26" ))
```

You don't need backpipes to write your code nicely, you just need to underwrite the principles of *semantic formatting*. Wait a second, I haven't written them down yet ...

**Comment by ctbrown** [comment]
Except what you didn't write the same code.  You meant:

    h1(
       div( class="color-green" ,
         div( class="text-bold",
           div( class="date", "2015-08-26" )
         )
      )

IMO, this is not as clear as my example, indentation or not..

**Comment by piccolbo** [comment]
I stand corrected.

**Comment by rodrigomurta** [comment]
This would be nice. Here is a StackOverflow related question. 
[Is right-to-left operator associativity in R possible?](http://stackoverflow.com/questions/31305342)
and this other related to operator visualisation in RStudio:
[http://stackoverflow.com/questions/32305096](is-it-possible-to-beautifully-display-the-pipeline-character-in-rstudio)

**Comment by ctbrown** [comment]
@rodrigomurta 

* The first of your SO links, [is-right-to-left-operator-associativity-in-r-possible](http://stackoverflow.com/questions/31305342/is-right-to-left-operator-associativity-in-r-possible) was previously documented above.

* The second returned a "page not found", try [is-it-possible-to-beautifully-display-the-pipeline-character-in-rstudio](http://stackoverflow.com/questions/32305096).

**Comment by ctbrown** [comment]
Also:

I just submitted a package to *CRAN* called `backpipe` that provides a "reverse pipe" (right-to-left) operator for both *magrittr* and *pipeR* (and any other forward left-to-right operator for that matter).  It can also be found here on [github](https://github.com/decisionpatterns/backpipe.git).

**Comment by rodrigomurta** [comment]
Wrong link syntax. Corrected. Tks!

**Comment by ctbrown** [comment]
The *backpipe* package has been accepted by CRAN, AFAIAC you can close this issue.

**Comment by smbache** [comment]
great!
