### ISSUE TITLE
New alias for `[[<-`

### ISSUE THREAD

**Issue by gaborcsardi** [smbache/magrittr#35]
I cannot find a functional equivalent of `[[<-`, maybe there isn't one. In which case it would be nice to have one, so that I can write

```r
list(a = 1, b = 2, c = 3) %>%
  set(b = "foo")
```

or maybe rather

```r
list(a = 1, b = 2, c = 3) %>%
  set("b", "foo")
```

The function `replace` is actually almost good, but it drops the attributes of the value, so 

```r
foo <- "foo"
class(foo) <- "bar"
list(a = 1, b = 2, c = 3) %>%
  replace("b", foo)
```

only work if I write

```r
foo <- "foo"
class(foo) <- "bar"
list(a = 1, b = 2, c = 3) %>%
  replace("b", list(foo))
```

Btw. while at it, maybe it makes sense to define `set` and `set2`, analogously to `extract`, and `extract2`.

**Comment by smbache** [comment]
I guess I forgot to close this: `inset` and `inset2` exists now.
