### ISSUE TITLE
History

### ISSUE THREAD

**Issue by krlmlr** [smbache/magrittr#44]
It's (sometimes) possible to access the result of the last pipe evaluation through `.Last.value`. This is restricted to interactive sessions, and it's not possible to access e.g. the second-to-last entry.

Use case: I'm performing a complex transformation on a data frame and use `%>% head` to view the first few lines of the result. Then I realize that in fact I want to see more, but to view the same results with `%>% View`, I need to re-run the entire pipe.

How about having `magrittr` memoize the last few (10? 20?) evaluations (with the RHS as descriptor) and provide access to it? This would also fix #43 (from a user's perspective).

**Comment by smbache** [comment]
I wouldn't think so, but you'd have to ask them ;)
