### ISSUE TITLE
A variant of assignment

### ISSUE THREAD

**Issue by kohske** [smbache/magrittr#5]
I'd be happy if magritter has assignment operator like %=>% (or %->%). For example,

```
Batting %>%
   group_by(playerID) %>%
   summarise(total = sum(G)) %=>% Batting_raw %>% 
   arrange(desc(total)) %=>% Batting_ordered_all %>% 
   head(5) %=>% Batting_head
```

Thus we can easily have objects that are generated during the call chain.
Objects should be generated in the environment calling this function.

I imagine this is easy to implement, but unfortunately I have no time to do it.

@kohske

**Comment by kykuo** [comment]
Can someone provide example code to use `->` in a chain? I can't figure out how to get around operator precedence without writing parentheses. Been wondering if there's something prettier than `%T>% assign`.

**Comment by rubenarslan** [comment]
@kykuo I've also been unable to get around that. I want pipes, where I first assign the result of an expensive operation and can then later interactively start from the assigned object (i.e. the second line in my example below).
I'm now using 

    `%->%` = function(val, var) { assign(deparse(substitute(var)),val, envir = parent.frame()) }

and can have pipes like this:

    lmer(scale(desire) ~ included * fertile_cont + (1|session),data=diary) %->%
        m_desire %>% 
        print_summary() %>%
        plot_all_effects() %>%
        plot_window_comparison(diary) %>%
        plot_curve(diary)

I think this is nice and makes sense, but I think the %->% is a bit too easy to overread.
