### ISSUE TITLE
Alias for set_class

### ISSUE THREAD

**Issue by vnijs** [smbache/magrittr#66]
Perhaps just:

      set_class <- `class<-`

**Comment by gaborcsardi** [comment]
If you need to add a new class and keep existing ones, then you would need something like

```r
add_class <- function(x, new_class) {
  if (new_class %in% class(x)) {
    x
  } else {
    class(x) <- c(new_class, class(x))
    x
  }
}
```

But I don't know which one people need more often. Also `set_class` might be confused with `setClass`.

**Comment by mostly-harmless** [comment]
I used:

set_class(c("compare_means",class(.)))

but add_class would be great as well

**Comment by smbache** [comment]
`set_class` added in 565eb9a6111fa432ab33284d13d59405621926a3 ;
