### ISSUE TITLE
%>% does not work well with data.table

### ISSUE THREAD

**Issue by vsalmendra** [smbache/magrittr#67]
I am trying to use %>% with data.tables but I had problems:

    x = data.table(cars)
    25 %>% x[speed == .] # Fails with: Error in function_list[[k]](value) : object 'speed' not found

    25 %>% {x[speed == .]} # Ok

**Comment by smbache** [comment]
The reason is that `speed == .` is essentially a nested call, in which case your first example is translated roughly into 

    25 %>% x[., '=='(speed, .)]

which is not what you want. However, magrittr is in fact doing what it is supposed to, and whenever you don't want the behaviour, you can use `{}` as you do.
