### ISSUE TITLE
Best practices in programming?

### ISSUE THREAD

**Issue by jennybc** [smbache/magrittr#68]
I just ran afoul of the "bare functions preceded by:: and :::" thing (#61). I am successfully using statements like `x %>% foo::yo %>% blah(foobar)` in a package I am developing, but tests were mysteriously failing on Travis. I now know that's due to differences in the CRAN and GitHub versions of `magrittr`. Lesson learned and I think I know what my options are going forward.

But the incident raises this question: are there certain ways of using `magrittr` that are safe in "interactive" analysis or in scripts that are categorically a bad idea in programming and inside packages?

I'm thinking specifically about `dplyr` and how @hadley provides two functions, e.g. `dplyr::select()` and `dplyr::select_()`, for use in analysis vs. programming, respectively. Is there anything analogous for `magrittr`?

**Comment by smbache** [comment]
I think this is mostly a mattr of preference. Personally I'm not too happy with `::` in chains/workflows, but like to import functions I use elsewhere, to keep the steps as clean as possible. When the CRAN version is updated at some point they should work as the github version.

I'm not sure I answered your question?

**Comment by jennybc** [comment]
No my question wasn't about double colons. It was about guidelines for using `magrittr` in packages. I have better questions on this and will maybe re-open this in future when I'm actively struggling with them and can be more specific.
