### ISSUE TITLE
Handling two (or more?) streams simultaneously

### ISSUE THREAD

**Issue by klmr** [smbache/magrittr#72]
This may be taking pipelines a bit too far but it may also be nice to have:

A common scenario I encounter is that I have two data sources which need to be processed in a certain way, and are then both fed into one function. As an example, consider the case of two non-tidy data sources which I want to join:

```r
a = data.frame(A=1:3, B=2:4, C=3:5)
b = data.frame(A=1:3, B=2:4, C=3:5) * 2
aa = melt(a, value.name='A')
bb = melt(b, value.name='B')
result = inner_join(aa, bb, by  = 'variable')
```

Somehow I imagine that it could be more readable to write this as a pipeline (at least once the simple `melt` operation here becomes a more complex chain of operations):

```r
result = {
    a %>%
    … %>%
    melt(value.name = 'A')
} %++%
{
    b %>%
    … %>%
    melt(value.name = 'B')
} %>%
inner_join(by = 'variable')
```

The `%++%` would somehow construct a stream “tuple” here.

I’m not even convinced myself that this has any advantage over the first, stream-less variant. I’m also not aware of any other programming languages which would support this, so there may not be much precedence (but visual languages where the developer constructs streams, such as Knime, do of course support this).

**Comment by smbache** [comment]
Sometimes I've wanted to do these kind of things, but I usually end up concluding that it is probably too much of the good stuff :)
