### ISSUE TITLE
NS versions of some common aliases, e.g. extract

### ISSUE THREAD

**Issue by smbache** [smbache/magrittr#74]
Some aliases, e.g. `extract <- '['`, while useful, are a little clumsy when used in pipelines.
Here is an example, `slice`, which is like `extract`, but adds a little "sugar". In particular, it allows for using column names in `data.frame` objects (via NS) and has two keywords which can be used in indexing: `.last` and `.all`, see below.

Not sure if this kind of stuff is too fancy for `magrittr` or should be placed somewhere else. On the one hand, I'd like to keep `magrittr` as small as possible, on the other I'd often like to use this myself.

```R
#' Slice a rectangular object
#'
#' This is an alternative to "[" for slicing data.frames or matrices. For
#' data.frames, \code{slice} supports non-standard evaluation in the sense that
#' column names are directly available, which is useful in pipelines. There is
#' also two new keywords: \code{.last} which evaluates to the number of rows or
#' columns respectively, and \code{.all} which evaluates to
#' \code{seq_len(NROW(.))}, and \code{seq_len(NCOL(.))}, respectively. The index
#' arguments defaults to NULL, so there is no need to add commas when e.g.
#' \code{j} is not used.
#' 
#' @param . data.frame or matrix
#' @param i the row index/indices or slicing expression
#' @param j the column index/indeces or slicing expression
#' @return a subset of the original data argument
#' @export
#' @examples 
#' iris %>% slice(1:10)
#' iris %>% slice(100:.last)
#' iris %>% slice(Species == "setosa")
#' iris %>% slice(.all, 3:.last)
#' iris %>% slice(, 3:.last)
#' iris %>% slice(.all %% 2 == 0)
#' iris %>% slice(1:5, .all %% 2 == 0)
slice <- function(., i, j)
{
  if (missing(i))
    i <- seq_len(NROW(.))
  else 
    i <- eval(call("substitute", substitute(i), 
                   list(.last = NROW(.), .all = seq_len(NROW(.)))))
      
  if (missing(j))
    j <- seq_len(NCOL(.))
  else 
    j <- eval(call("substitute", substitute(j), 
                   list(.last = NCOL(.), .all = seq_len(NCOL(.)))))
  
  if (is.data.frame(.))
    eval(call("[", ., i, j), ., parent.frame())
  else
    eval.parent(call("[", ., i, j))
}
```

**Comment by smbache** [comment]
Just recalled that `slice` is used in `dplyr` so probably some other name is preferable.

**Comment by gwerbin** [comment]
With regard to your comment about naming:

I find that some of the built-in aliases are either too verbose relative to what they alias, or unintuitive, or both. My .Rprofile has a bunch of replacements. I'm not saying they're ideal but I think this might be a good direction:

    in1 <- `[`
    in2 <- `[[`
    inS <- `$`
    set_in1 <- `[<-`
    set_in2 <- `[[<-`
    set_inS <- `$<-`

The only reason I don't use the raw command is that the "`" key is so darn hard to reach on a US keyboard. And I'd rather not type a big long word `extract` when the original solution is just two characters `[` and `]`. Sometimes I find it easier to just use `%>% {.[ ... ]}` than the standard `magrittr` aliases. Also these aliases are much more distinctive and therefore much less likely to get masked by another package (again, thinking about `extract`).
