### ISSUE TITLE
Add a stack?

### ISSUE THREAD

**Issue by krlmlr** [smbache/magrittr#76]
Example -- computation of x² + y²:

```
x %>% push %>% multiply_by(pop()) %>+% 
y %>% push %>% multiply_by(pop()) %>% add(())
```

The (new?) `%>+%` operator pushes *and* starts a new pipe, something like

```
`%>+%` <- function(x, y) { push(x); y }
```

An alternative approach to #72 and #44, and probably to other problems. Every new pipe clears the stack -- that's why it would be preferably built into `magrittr` and not into an external package.

**Comment by smbache** [comment]
I'm thinking this would `push` more confusion than it would `pop`? ;)

**Comment by krlmlr** [comment]
Of course,

```
confusion %>%
  is_less_than(benefit) %>%
  assert
```

There might be no need to build this into `magrittr` after all -- there are other ways to limit the size of the stack.
