### ISSUE TITLE
Need simpler way of putting conditionals inline with %>%

### ISSUE THREAD

**Issue by wch** [smbache/magrittr#8]
Here's an example of what I'd like to do:

```
rowcount <- TRUE
mtcars %>% function(x) if(rowcount) nrow(x) else x
# [1] 32

rowcount <- FALSE
mtcars %>% function(x) if(rowcount) nrow(x) else x
# [prints out mtcars]
```

But the syntax is clunky.

One thought is to make `x %>% NULL` simply return x. Then, because `if(F) 123` returns NULL, `x %>% if(F) 123` would just return `x`. But this doesn't quite work since the `if` isn't evaluated before being processed by `%>%`.

Any thoughts on how to do this cleanly?

**Comment by smbache** [comment]
This at all interesting anymore, as you can do

```R
mtcars %>% {if(rowcount) nrow(.) else .}
```

to take the initial example? If so, you're welcome to re-open...
