### ISSUE TITLE
Changing the default alias/placeholder from `.` -- possible?

### ISSUE THREAD

**Issue by gwerbin** [smbache/magrittr#81]
I would _love_ the ability to be able to do something like:

    options("magrittr.placeholder" = "..")

and then be able to free up `.` for other uses, like the function in `plyr` (occasionally still nice instead of `dplyr`), formulas (I don't know how this interacts with the alias but it seems like it could be fragile), , and of course `dplyr::funs` (again, I don't know what the interaction is like but I'd rather not have to think about it).

Of course, I'd also like to be able to do `options("dplyr.funs.placeholder" = "._")`, but I feel like it'd be more powerful to have the functionality come from `magrittr` first.

**Comment by hadley** [comment]
I think this is a bad idea - adding a global option to control this sort of behaviour will introduce hard to find bugs.

**Comment by smbache** [comment]
AFAIK none of the above examples pose any problems, except perhaps in very obscure constructions ...

**Comment by gwerbin** [comment]
Understood, thanks for the quick reply.

**Comment by bramtayl** [comment]
There's an issue with formulas:
```r
example = 
  data.frame(x = 1:10,
             y = 1:10)

# works
example %>% lm(y ~ .)

# doesn't
lm(y ~ . , example)
```

**Comment by smbache** [comment]
This is how you want to do it

```R
example %>% lm(y ~ ., .)

#or
example %>% lm(formula = y ~ .)

#or
example %>% lm(y ~ ., data = .)
```

**Comment by bramtayl** [comment]
Hmm, made a simplified example with a bug. Here was the original context, and but given the working solution above, I don't think this is a magrittr problem at all.

data = 
  data_frame(a = rnorm(10),
             b = rnorm(10),
             c = "delete",
  extract(c(1:2, which(names(.) == "quality")))

data.training = 
  data %>%
  slice(1:5)

# doesn't work
data.test = 
  data %>%
  slice(6:10) %>%
  mutate(
    c.predict = 
      lm(c ~ . , data.training) %>%
      predict(data.test) %>%
      unname)

# works
data.test = 
  data %>%
  slice(6:10) 

data.test$c.predict = 
  lm(c ~ . , data.training) %>%
  predict(data.test) %>%
  unname

**Comment by smbache** [comment]
You're trying to use data.test before its defined

**Comment by bramtayl** [comment]
Oops again. See edit above. The error I'm getting is Error in terms.formula(formula, data = data) : 
  invalid term in model formula
