### ISSUE TITLE
%<>% inside mutate

### ISSUE THREAD

**Issue by bramtayl** [smbache/magrittr#89]
It would be convenient if %<>% worked inside dplyr's mutate. E.g.

    library(dplyr)
    library(magrittr)

    data = data_frame(a = 2) %>%
       mutate(a %<>% add(1))

**Comment by abresler** [comment]
Ohh love this idea!

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

**Comment by smbache** [comment]
Could you post this @ dplyr github page?
Not that I haven't wanted to do this sometimes myself but I don't think this will go through.

**Comment by bramtayl** [comment]
Done. See

hadley/dplyr#1189
