### ISSUE TITLE
Proposition: Concatenation operator

### ISSUE THREAD

**Issue by krlmlr** [smbache/magrittr#90]
Would you support

```
`%+%` <- function(x, y) c(x, y)
```

? This allows:

```
> 1 %+% 2 %+% 3
[1] 1 2 3
```

I think this sort of fits the scope of `magrittr`:

- I use `%>%` when I "forgot" to apply some transformation to a value
- I use `%+%` when I "forgot" to append something to a value

**Comment by smbache** [comment]
Not a fan of this; one can simply do `x %>% c(y)` or `x %>% append(y)`; adding an operator for this purpose is not worth it IMO.
