### ISSUE TITLE
"do this only if" syntax for piped functions

### ISSUE THREAD

**Issue by franknarf1** [smbache/magrittr#91]
It would be nice if one could write

    rnorm(1) %>%  if (. > 0) sqrt            %>% add(1)    # should work?
    rnorm(1) %>% {if (. > 0) sqrt(.) else .} %>% add(1)    # works

The second way arguably defeats the goal of avoiding clutter, with unnecessary curly brackets and parentheses; explicit `.` as the first argument of the function; and a redundant `else` clause.

If making the first line work as-is is not an option, maybe a new function like `IF` or `doif` could be defined that can only be used here (right after a pipe) and would fill in the omissions when constructing the function.

----

I see that an example like the second line appears in the vignette as a good use of an anonymous function, but I think simplifying further would be better so long as it doesn't go against the `magrittr` design philosophy somehow. Here's the SO post that got me thinking about this: http://stackoverflow.com/questions/30604107/r-conditional-evaluation-when-using-the-pipe-operator

**Comment by smbache** [comment]
This has been discussed before; with other names such as `when` and `fif` proposed. 
It was closed; and actually `when` was added to @hadley 's `purrr`: https://github.com/hadley/purrr/blob/master/R/when.R

**Comment by franknarf1** [comment]
Okay, thanks for the reference. I think I was unclear, since that isn't really what I was looking for, though.
