### ISSUE TITLE
increment, decrement operators as pipe

### ISSUE THREAD

**Issue by ckluss** [smbache/magrittr#92]
Hi

would it be usefull to have operators to write

x <- 2
x %+=% 3 %-=% 1

instead of 

x <- 2
x %<>% add(3) %>% subtract(1)
x

(for all the magrittr aliases )

Thank you very much für the great package.

**Comment by hadley** [comment]
Why is that better than `x + 3 - 1`?

**Comment by ckluss** [comment]
I do not understand your question, if x is complex (e.g. multidimensional array) it is much better than writing x  twice. 

If you ask this question, than you can have the same question why there are operators like "add", "substract" and so on...or I have a flaw

**Comment by smbache** [comment]
How about 

```R
x %<>% +3 %>% -1
```

**Comment by ckluss** [comment]
oh that is cool, thank you very much!

**Comment by smbache** [comment]
;)

Also nice with ggplots
