### ISSUE TITLE
Magrittr logo

### ISSUE THREAD

**Issue by gaborcsardi** [smbache/magrittr#96]
Does magrittr have an "official logo"? There is the hex at the top of the README, and there is the image at https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html. Is either of them _the logo_? 
And there is also the pipe logo, but I am not sure if one can use that as it is probably copyrighted.

**Comment by smbache** [comment]
I honestly have no idea about whether any of it is copyrighted. I guess nothing is official, but I usually think of the hex. Any particular thoughts?

**Comment by gaborcsardi** [comment]
I think the hex is nice, but it would be great to have a non-hex version, that looks better on web pages. E.g. just "extracting" a rectangle from the middle of the hex. Probably without the background.

**Comment by smbache** [comment]
The hex is publically available as vector graphics. Should be pretty easy to extract and modify to your wishes. You're welcome to see what you can come up with :)

**Comment by gaborcsardi** [comment]
OK, here is a quick try: https://github.com/gaborcsardi/magrittr/tree/logo#----
I am not saying that it is particularly good. :)

**Comment by smbache** [comment]
I think it looks good.. It seems to me though that the horizontal alignment of ´`%>%` is slightly off to the left, and that the vertical alignment of text below is slightly off in upward direction?

**Comment by gaborcsardi** [comment]
OK, I fixed the horizontal alignment, inkscape is playing tricks on me.... 
Fixed the vertical, too. That was theoretically OK, but the long stem of the p's made it look as if it was off.

Btw. it would be nice to get rid of the background, but if I just delete it, it does not look too good.

**Comment by gaborcsardi** [comment]
Btw. I also moved around the images a bit. I moved them into `inst`, so that they are installed with the package. If you don't like this, I can move them back, or into a `media` (or whatever) folder, and then ignore it when building the R package.

**Comment by smbache** [comment]
Looks much better. inst is fine with me. Not sure how a transparent bg would work out...
