### ISSUE TITLE
mispelling of the indefinite article: the french word is "une pipe" not "un pipe"

### ISSUE THREAD

**Issue by wabarr** [smbache/magrittr#97]
This is misspelled in the logo and in readme.MD.  I am not sure if this is on purpose or by accident.  If it is an accident, I am happy to submit a pull request.

**Comment by smbache** [comment]
Thanks Andrew. It's no accident: a "computer pipe" is masculine. ;-)

**Comment by wabarr** [comment]
Interesting, thanks!  I wonder why that is?  It could be because *le pipe* is a loan-word from English.  [This academic study](http://ijb.sagepub.com/content/10/3/253.short) suggests that loan-words into French typically get assigned the masculine gender.

**Comment by JoshOBrien** [comment]
Ah, thanks. Still grates though, but I guess that's my problem ;)
